### ISSUE TITLE
Docs no longer working

### ISSUE THREAD

**Issue by olimart** [excid3/tailwindcss-stimulus-components#103]
Following the upgrade to Stimulus 3, docs are no longer working.

Browser's console raises `TypeError: Module specifier, '@hotwired/stimulus' does not start with "/", "./", or "../". `

**Comment by excid3** [comment]
PRs welcome

**Comment by excid3** [comment]
Example: https://github.com/excid3/tailwindcss-stimulus-components/blob/master/docs/index.html#L300-L313

**Comment by olimart** [comment]
closed by #105

**Comment by krongk** [comment]
need to add below code to config/importmap.rb:

`pin "tailwindcss-stimulus-components", to: "https://unpkg.com/tailwindcss-stimulus-components/dist/tailwindcss-stimulus-components.modern.js"`
