### ISSUE TITLE
"slideover#_hide" is typo?

### ISSUE THREAD

**Issue by philipithomas** [excid3/tailwindcss-stimulus-components#113]
Hey Chris! In the ReadMe you reference `slideover#_hide` in the example code, but the demo never uses the underscore - only `slideover#hide`. Is this an error, or does the underscore have some undocumented functionality?

PS this library is great - thanks!

**Comment by excid3** [comment]
Yeah I think that should be `slideover#hide` as the underscore version is more the internal API that's used. We don't use any underscore methods in the example page: https://github.com/excid3/tailwindcss-stimulus-components/blob/master/docs/index.html

**Comment by philipithomas** [comment]
Ok - I'm seeing weird behavior in my app   when I remove the underscores: https://www.loom.com/share/4a9ff7a3b98949c6ad1adf71d49e9b71

**Comment by ozovalihasan** [comment]
The demo is working as expected. [Its action](https://github.com/excid3/tailwindcss-stimulus-components/blob/2f25e3ba3c692ef2eba66975a20581ccfe0aaef5/docs/index.html#L32) is `slideover#toggle`. So, it should be updated as `slideover#toggle`, instead of `slideover#hide`

**Comment by Merovex** [comment]
In the javascript file, there's example html at the top of the file. It uses `_hide` and `_show`. Would be nice if that was updated. Not sure if this is closeable yet.
