### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by firedev** [excid3/tailwindcss-stimulus-components#118]
Is it me or none of the examples on https://excid3.github.io/tailwindcss-stimulus-components/ work?

**Comment by excid3** [comment]
Share some details about what you're using and seeing.

**Comment by firedev** [comment]
I saw only html+css, none of the controllers worked. But it's back again. Must be something with github pages.

**Comment by firedev** [comment]
Hmm so I guess there is an issue after all:

https://excid3.github.io/tailwindcss-stimulus-components/

```
An import map is added after module script load was triggered.
excid3.github.io/:1 Uncaught TypeError: Failed to resolve module specifier "@hotwired/stimulus". Relative references must start with either "/", "./", or "../".
```

Refresh and it works again.

**Comment by excid3** [comment]
The importmap shim will let that error happen, it's how the shim works I guess.
