### ISSUE TITLE
Dropdown component on hover

### ISSUE THREAD

**Issue by johnnypea** [excid3/tailwindcss-stimulus-components#124]
I tried `data-action="mouseenter->dropdown#show mouseleave->dropdown#hide"`, but couldn't get it work. Any suggestions? Thanks.

**Comment by ozovalihasan** [comment]
@johnnypea I don't know how to build this feature by using Stimulus. Let me share my alternative solution by [styling based on parent state](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state), which is a feature of tailwindcss.

```html
<div class="group" >
    Any element
    <div class="hidden group-hover:block">
        Example menu
    </div>
</div>
```

**Comment by johnnypea** [comment]
I see, thank you for the prompt answer.

**Comment by pySilver** [comment]
@ozovalihasan while solution with groups is fine (unless you need some custom entering / leaving clases) I'd like to ask why we need this check `this.element.contains(event.target) === false` in a first place here:

https://github.com/excid3/tailwindcss-stimulus-components/blob/master/src/dropdown.js#L132

?

**Comment by pySilver** [comment]
I assume its done to support close-on-click-outside which can be handled like that: https://stimulus-use.github.io/stimulus-use/#/use-click-outside
