### ISSUE TITLE
Modal doesn't close if doesn't have 'inset-0` class

### ISSUE THREAD

**Issue by Tolchi** [excid3/tailwindcss-stimulus-components#141]
I need the modal to be positioned top left instead of in the middle of the window. So I added top-0 left-0 class. But for the surprise, if I click the background the modal doesn't close itself as it should be. Clicking background closes modal with inset-0 class. Don't know why this is happening.
I tried to add data-modal-allow-background-close='true' but without success

version of TailwindcssStimulusComponents: v2.2.2

**Comment by RubyBrewsday** [comment]
+1 this, just ran into the same issue

**Comment by excid3** [comment]
We've switched to the `<dialog>` element now which provides the `::backdrop` instead and is much simpler to use.
