### ISSUE TITLE
Extending Toggle only works on the connect action?  Trying to add an accordion functionality.

### ISSUE THREAD

**Issue by jasper502** [excid3/tailwindcss-stimulus-components#143]
Staring with something as simple as this to confirm its working.

```
import { Toggle } from "tailwindcss-stimulus-components"

export default class extends Toggle {

  connect() {
    super.connect();
    console.log("Toggle Super")
  }

  toggle(event) {
    super.toggle(event);
    console.log("Toggle")
   }

}
```

The "Toggle Super" fires for each toggle group on my page.  The toggles still work but the "Toggle" console action is not triggered.  Trying to have an accordion functionality.

**Comment by rockwellll** [comment]
Have you found the issue?. Your code seems to be correct
