### ISSUE TITLE
dropdown.js: what is `hasButtonTarget`?

### ISSUE THREAD

**Issue by MaffooClock** [excid3/tailwindcss-stimulus-components#146]
In dropdown.js, the `connect()` and `disconnect()` methods perform a conditional action based on `this.hasButtonTarget`, but it doesn't appear to be defined nor used anywhere, and therefore seems to have no purpose.

https://github.com/excid3/tailwindcss-stimulus-components/blob/c29ad8584a3d31a36db58464a13b029a42b83c8b/src/dropdown.js#L41-L43

https://github.com/excid3/tailwindcss-stimulus-components/blob/c29ad8584a3d31a36db58464a13b029a42b83c8b/src/dropdown.js#L49-L51

Is this extra cruft that should be removed?

**Comment by excid3** [comment]
Stimulus defines those automatically for targets. https://stimulus.hotwired.dev/reference/targets#properties
