### ISSUE TITLE
For Rails 7, download tailwindcss-stimulus-components to vendor/javascript

### ISSUE THREAD

**Issue by justinko** [excid3/tailwindcss-stimulus-components#153]
This is just to help others that might be wondering why they're missing styles after upgrading to Rails 7.

If you're using [tailwindcss-rails](https://github.com/rails/tailwindcss-rails) with Rails 7, you need to specify how to find the CSS classes [tailwindcss-stimulus-components](https://github.com/excid3/tailwindcss-stimulus-components) uses (e.g. the ones in modal).

Here's what you need to do:

1. Download to vendor/javascript so tailwindcss-rails can find the CSS classes: `bin/importmap pin tailwindcss-stimulus-components --download`
2. Add `vendor/javascript` to your tailwind config:

```
module.exports = {
  content: [
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*',
    './app/lib/form_builder.rb',
    './vendor/javascript/tailwindcss-stimulus-components.js'
  ],
}
```

That's it! All the tailwind classes that this library uses will now be included in your Rails app.

**Comment by Petercopter** [comment]
I was poking around for a solution as well, it seems reasonable to use safelisting as well:

https://stackoverflow.com/questions/70597881/exclude-a-class-being-tree-shaken-by-tailwind

**Comment by matthewsalan** [comment]
@justinko DId you have to do anything else to get the animations to work?  I _think_ I set up everything correctly to use the `alert` component, but the animations don't work as in the example when the alert is displayed and dismissed.  Clicking on the close button does work, but there is a delay in between clicking and when the alert goes away.

Separately, setting `data-alert-dismiss-after-value` to a value of `200` milliseconds does cause the alert to dismiss, but again the animation is not working.

**importmap.rb**
```
# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "https://ga.jspm.io/npm:@hotwired/stimulus@3.1.1/dist/stimulus.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin "tailwindcss-stimulus-components" # @3.0.4
pin_all_from "app/javascript/controllers", under: "controllers"
```
**controllers/application.js**
```
import { Application } from "@hotwired/stimulus"
import { Alert } from "tailwindcss-stimulus-components";

const application = Application.start()
application.register('alert', Alert)

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```
**application.js**
```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
```
**controllers/index.js**
```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
```

Any idea of what I'm missing?
