### ISSUE TITLE
Does Autsave require ujs?

### ISSUE THREAD

**Issue by philipithomas** [excid3/tailwindcss-stimulus-components#157]
I'm trying to use the Autosave controller. I notice it [references](https://github.com/excid3/tailwindcss-stimulus-components/blob/master/src/autosave.js#L16):

>       Rails.fire(this.formTarget, 'submit')

To confirm - is this using UJS? These are Stimulus controllers, but I've been unable to find a `Rails.fire` method in any of the Stimulus docs.  

Depending on the resolution - I can update the docs to specify the dependency for autosave.

**Comment by Merovex** [comment]
Yes. The Autosave Controller uses ujs. And, I'm getting the following error since it is not included:

`ReferenceError: Can't find variable: Rails`

**Comment by dewey** [comment]
Related, there was a MR merged recently that removed the `Rails.fire` call mentioned above: https://github.com/excid3/tailwindcss-stimulus-components/pull/172
