### ISSUE TITLE
Using focus event for opening modals can cause a bug.

### ISSUE THREAD

**Issue by scotteknight** [excid3/tailwindcss-stimulus-components#17]
Hey Chris, thanks for the awesome components! I have a modal that gets opened using `data-action="focus->modal#open"` (on an input element).
This works fine but if you switch to another window and back again while the modal is open then the open action is called again and it adds another background element to the body. Then you can't fully close out of the modal.
This could get fixed by adding `e.target.blur();` to the open method. Or maybe there's a more comprehensive way to check if the modal is already open within the open method so that it doesn't get called again.

**Comment by excid3** [comment]
That's probably not a bad solution. I recently had something similar when replacing Rails confirm dialogs and if you hit enter after clicking the link, it would submit the link (not the modal) and trigger the browser confirm.

In general, you don't ever want the triggering element to continue to have focus after the modal opens, so I think this would be a good solution unless anyone can think of issues with this approach.

Want to submit a PR?

**Comment by scotteknight** [comment]
Sounds good, I'll submit a PR

**Comment by ggladden** [comment]
Thought I'd chime in here, this solution actually breaks my use case. I'm trying to open a modal on a scroll event on the document. As the document object doesn't have a blur() method an error is thrown.

**Comment by excid3** [comment]
@ggladden Want to submit a PR that checks if `e.target` is defined? Sounds like it would fix your issue?

**Comment by ggladden** [comment]
Will do!
