### ISSUE TITLE
Permit use Turbo frame on tabs click -Possible solution-

### ISSUE THREAD

**Issue by sergitejada** [excid3/tailwindcss-stimulus-components#178]
I have been using the tabs component and it does not accept Turbo Frame. 
The "click->tabs#change" uses event.preventDefault() and does not allow to follow the url of the link.
And when using Turbo-Frame you need to make a request get
My option create a new function and remove event.preventDefault()
```
    change_with_url(event) {
        // If target specifies an index, use that
        if (event.currentTarget.dataset.index) {
            this.index = event.currentTarget.dataset.index

            // If target specifies an id, use that
        } else if (event.currentTarget.dataset.id) {
            this.index = this.tabTargets.findIndex((tab) => tab.id == event.currentTarget.dataset.id)

            // Otherwise, use the index of the current target
        } else {
            this.index = this.tabTargets.indexOf(event.currentTarget)
        }

        window.dispatchEvent(new CustomEvent('tsc:tab-change'))
    }
```

I think another attribute could be created

**Comment by excid3** [comment]
You'll have to provide an example of what you're doing so we can understand what you're trying to do.

**Comment by sergitejada** [comment]
![image](https://user-images.githubusercontent.com/49126831/215540214-ce08722f-3634-493c-91c5-82a194176525.png)
I'm using Turbo-frame inside a tab action
By default the tab don't permit

**Comment by excid3** [comment]
You should put the turbo frame inside the tab contents and use the lazy load feature so it only loads when visible.
