### ISSUE TITLE
Tabs not working with the select / dropdown

### ISSUE THREAD

**Issue by wdiechmann** [excid3/tailwindcss-stimulus-components#186]
DISCLAIMER:
I may easily present this on its head - and still be wrong! The Tabs component may work 100% and I could be the culprit not finding my ways through the documentation -- and I am painfully aware of @joshmfrankel 's PR which probably does the work of this blunt instrument in a very elegant way. If that be the case I apologize for consuming your bandwidth!

ISSUE:
the first Tailwind component in the [tabs selection](https://tailwindui.com/components/application-ui/navigation/tabs) changes from a dropdown to a `<nav><a>` from `sm` upwards -- but I've had no luck using the Tabs component for this, so I wrote a tiny `select_controller` with this method 
 
```
  change(e){
    let options = e.currentTarget.options
    let index = options[e.currentTarget.value].value
    let tabs = document.querySelectorAll("[data-tabs-target='panel']")
    tabs.forEach((tab, i) => {
      if (i == index) {
        tab.classList.remove('hidden')
      } else {  
        tab.classList.add('hidden')
      }
    })
  }
```

and strapped it on the knees of the `<select>` tag  like so (should you ponder on the semiotics, do like I did - go enjoy [the best component gem IMHO](https://github.com/phlex-ruby/phlex) )

```
            # Dropdown menu on small screens
            div( class: "sm:hidden") do
              label( for: "current-tab", class: "sr-only") {"Select a tab"}
              select( id: "current-tab", 
                name: "current-tab", 
                data: { action: "change->select#change", index: 0 },
                class: "block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                ) do
                index = 0
                @tabs.each do |tab|
                  option( value: index, data: { tabs_target: "tab", turbo_frame: tab[:turbo_frame], content_loader_url_param: tab[:url], content_loader_target_param: tab[:turbo_frame] } ) { tab[:label] }
                  index = index + 1
                end
              end
            end

```

I'm sure @excid3 or anyone with his level of Ruby/JS-Fu will have little trouble glueing it on to the `tabs_controller.js` - or even better, make the tabs_controller work with the `select` ( I have a feeling that adding a test for `options[e.currentTarget.value].value` might do the trick )

**Comment by excid3** [comment]
We've added support for radio buttons on the tabs controller, so I bet we can use the same approach for the select. Will have to try that out.
