### ISSUE TITLE
How to open tab if it is not the first one?

### ISSUE THREAD

**Issue by AlainPilon** [excid3/tailwindcss-stimulus-components#19]
The current code sample for the tabs always select the first one, how can we set any other tabs as default? Or an even better solution would be to keep the last opened tab in a cookie I guess :-S

**Comment by excid3** [comment]
Add `data-tabs-index="2"` to the same tag as your `data-controller` and that should do it. 

We keep track of which tab is selected using that index in the HTML: https://github.com/excid3/tailwindcss-stimulus-components/blob/master/src/tabs.js#L30
