### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gregmolnar** [excid3/tailwindcss-stimulus-components#191]
There are quite a few unreleased changes(like dropping Rails UJS dependency for Autosave) since the last release: 

https://github.com/excid3/tailwindcss-stimulus-components/compare/v3.0.4...master

Would it be possible to cut a new release?

**Comment by excid3** [comment]
#188 will be our new release which cleans up a ton of stuff and adds better animation support.

I just need to figure out how to get these damn tests working. 🙃

**Comment by gregmolnar** [comment]
You guys are writing tests??? :D Just delete them and you are all set! :)
Do you happen to know how to use an unreleased version with importmaps? If I pin https://raw.githubusercontent.com/excid3/tailwindcss-stimulus-components/master/dist/tailwindcss-stimulus-components.modern.js it complains about the content type being plain/text.

**Comment by excid3** [comment]
I'd just copy it into your repo for now. I think GitHub intentional sets the content-type so you can't do that.

**Comment by gregmolnar** [comment]
Thanks!
