### ISSUE TITLE
Active tabs styling is broken in version 4

### ISSUE THREAD

**Issue by spryffee** [excid3/tailwindcss-stimulus-components#194]
#### How to reproduce?

1. Install tailwindcss-stimulus-components@4.0.x
2. Use the code snipped provided as example https://github.com/excid3/tailwindcss-stimulus-components/blob/master/docs/tabs.md

The active tab styling doesn't work. If I revert to tailwindcss-stimulus-components@3.0.x everything works fine.

**Comment by excid3** [comment]
I've updated the example to use the Stimulus Classes API that we now use. 👍 

https://github.com/excid3/tailwindcss-stimulus-components/commit/2a4c7232185fbcc4926c14176e0d3fc99aa82964
