### ISSUE TITLE
Specify prefix for tailwind classes

### ISSUE THREAD

**Issue by Vin0uz** [excid3/tailwindcss-stimulus-components#201]
Hey👋

I've been trying to use components from this beautiful repo in a legacy codebase, which is somewhere in the change from bootstrap to tailwind. To make it safer, tailwind classes are prefixed with `tw-`

It's safer but it makes the usage of this lib impossible.. or at least not the components I've tried (popover/modal), because `tw-hidden` stays on, as the lib is dealing with `hidden` 

Do you think there's a way we could explicitly tell components to use a prefix for tailwind classes ? 😬 

As a 🩹 I've tried to use custom transition classes, but no luck..

**Comment by excid3** [comment]
For a temporary workaround, you can define `.hidden { display: none; }` which won't conflict with Bootstrap since they use `.d-none`

Long-term it would be great to have those configurable.
