### ISSUE TITLE
Issue when using `data-tabs-update-anchor-value="true"` and linking to a specific anchor from another page

### ISSUE THREAD

**Issue by woller** [excid3/tailwindcss-stimulus-components#204]
https://github.com/excid3/tailwindcss-stimulus-components/assets/23448075/63a6662e-4542-45b8-9542-4e33a4af29c3

As the title says, there seems to be a bug, when I use both `data-tabs-update-anchor-value="true"` and link to a specific anchor.

**Expected behavior**
The user clicks a link to a specific anchor and the corresponding tab is selected.

**Actual behavior**
The user clicks the link, but the first tab is always selected.

I haven't been able to figure out what is going wrong, but if anyone has any pointers, I'll give it another go.

The bug is reproduced in [this repo](https://github.com/woller/reproduce-anchor-bug)

**Comment by snake117** [comment]
I'm currently encountering this same issue and I have not been able to find a solution. Any advice/help would greatly be appreciated.
