### ISSUE TITLE
CDN Minified version does not appear to respect `data-toggle-class` for toggle

### ISSUE THREAD

**Issue by tinney** [excid3/tailwindcss-stimulus-components#215]
When using the package with rails importmaps the following is used: 
`pin "tailwindcss-stimulus-components", to: "https://ga.jspm.io/npm:tailwindcss-stimulus-components@4.0.4/dist/tailwindcss-stimulus-components.module.js"`

This version of the package does not seem to use the data-toggle-class and applies `hidden` to all toggle elements.

**Comment by jdpahl122** [comment]
Can confirm on Jumpstart pro this isn't working as well

**Comment by excid3** [comment]
The demo site uses it from CDN just fine? https://excid3.github.io/tailwindcss-stimulus-components/
