### ISSUE TITLE
Popover doesn't support `translate-x` and `translate-y` values like mentioned in the doc

### ISSUE THREAD

**Issue by luciengeorge** [excid3/tailwindcss-stimulus-components#231]
Hello,

First of all thank you for the hard work that was put into this gem.

I was just trying to implement the popover stimulus component and noticed that the `translate-x` and `translate-y` had no effect on the position of the popover. After doing some digging, I realised that the values are not listed in the [controller's values](https://github.com/excid3/tailwindcss-stimulus-components/blob/main/src/popover.js#L26-L29) and thus not supported like [the docs](https://github.com/excid3/tailwindcss-stimulus-components/blob/main/docs/popover.md) mention.

Thank you!

**Comment by excid3** [comment]
The docs are outdated. You would apply it with the `enter` and `leave` data attributes for transitions.

**Comment by excid3** [comment]
Docs are now updated. https://github.com/excid3/tailwindcss-stimulus-components/blob/main/docs/popover.md

**Comment by luciengeorge** [comment]
Thank you 🙏
