### ISSUE TITLE
Flattpickr not working inside Slideover?

### ISSUE THREAD

**Issue by devrizwanali** [excid3/tailwindcss-stimulus-components#246]
[Stimulus flatpickr](https://github.com/adrienpoly/stimulus-flatpickr) not working inside [Slideover](https://github.com/excid3/tailwindcss-stimulus-components/blob/main/docs/slideover.md)

it seems like ```z-index``` issue but the faltpickr already have the z-index value 99999.

```
flatpickr-calendar.open {
    display: inline-block;
    z-index: 99999;
}
```

Here is the minimal code of the issue.  

https://github.com/devrizwanali/slideover

https://github.com/excid3/tailwindcss-stimulus-components/assets/26557936/efb97bf5-894b-4661-8858-085570a7a42e

**Comment by excid3** [comment]
This thread suggests using `{static: true}` with Flatpickr: https://github.com/flatpickr/flatpickr/issues/1502

Doesn't seem to be an issue with TSC, but with Flatpickr's interactions with `dialog` elements so their issues are a better place for this.
