### ISSUE TITLE
Back button breaks modal

### ISSUE THREAD

**Issue by scotteknight** [excid3/tailwindcss-stimulus-components#25]
I noticed that while the modal is open, if you navigate to another page and then go back, or if you hit back then forward while the modal is open, then you can't completely close the modal.
I wonder if using the disconnect() lifecycle method in stimulus to close the modal would fix it?

**Comment by excid3** [comment]
That would make sense to me. You want to try that? You should be able to edit the controller inside your node_modules folder to add it.

If not, can you build a quick and dirty example that showcases it?

**Comment by scotteknight** [comment]
I was able to make it work by adding: 
```
disconnect() {
  this.close();
}
```
but then I had to change in the close method:
```
if (e) e.preventDefault()
```
since there is no dom event.

**Comment by excid3** [comment]
Looks good to me. Want to PR it?

**Comment by scotteknight** [comment]
Will do!

**Comment by excid3** [comment]
🤘 Thanks Scott!

**Comment by excid3** [comment]
Fixed by #26
