### ISSUE TITLE
Tooltips with tippy.js

### ISSUE THREAD

**Issue by excid3** [excid3/tailwindcss-stimulus-components#3]
We can import tippy.js and have a stimulus wrapper around it pretty easily.

We'll need to also add css-loader to webpacker so it will compile the CSS from the library so we can provide it as well.

**Comment by richjdsmith** [comment]
I saw this after is submitted a PR for really basic inline tooltips or popovers. 🙃

**Comment by richjdsmith** [comment]
Reduce dependencies and size. 

I'll play around with it to see what needs to be done to ensure there's no funny business with regards to positioning. One downfall of this route vs tippy.js is there are currently no easy ways to add animations to Tailwind.

**Comment by excid3** [comment]
Yeah, I wonder if we could use like https://daneden.github.io/animate.css/ with it.

**Comment by excid3** [comment]
I think I'm just going to skip tooltips. Tippy is easy enough to make Turbolinks compatible.

```
import tippy from 'tippy.js';
import 'tippy.js/dist/tippy.css';
document.addEventListener("turbolinks:load", () => {
  tippy(document.querySelectorAll('[data-tippy-content]'))
})
```
