### ISSUE TITLE
Target Tabs through href/id

### ISSUE THREAD

**Issue by timmyd87** [excid3/tailwindcss-stimulus-components#38]
I would love to see the ability to target/switch between tabs using a button or link with a href and an id. I've been working on a wizard form and it would make the user experience better to have multiple ways to jump between tabs.

**Comment by excid3** [comment]
For now, I just added support by index, but next I'll add href support. 👍

**Comment by excid3** [comment]
Also updated the docs with an example link that's outside the tabs.

https://excid3.github.io/tailwindcss-stimulus-components/

**Comment by excid3** [comment]
And pushed a new version that allows changing tabs with `data-id`. Readme has been updated to include instructions as well.

**Comment by timmyd87** [comment]
Amazing Chris! Thanks for the speedy response!!
