### ISSUE TITLE
Adding Slide-Over Functionality

### ISSUE THREAD

**Issue by snake117** [excid3/tailwindcss-stimulus-components#39]
TailwindUI recently added [Slide-overs](https://tailwindui.com/components/application-ui/overlays/slide-overs) to there offering of pre-built components. Would it be possible to include the functionality for this kind of component in this package? It seems like it would make a great addition.

**Comment by excid3** [comment]
Sure! I think they're pretty much like our [Toggle](https://github.com/excid3/tailwindcss-stimulus-components#toggle) but with transitions right?

**Comment by snake117** [comment]
Great! That's pretty much what I was thinking. Separating the two and implementing the transition would probably save time and lead to cleaner code.

**Comment by excid3** [comment]
I agree, although I could certainly see adding transitions to the Toggle since they don't really need to be instant. Might be able to extend it and support both and just have two separate examples.

**Comment by mihaic195** [comment]
Would really much appreciate this!

**Comment by williamkennedy** [comment]
You can actually see a good example of this here https://dev.to/mmccall10/tailwind-enter-leave-transition-effects-with-stimulus-js-5hl7

If enough people want it, I can add transitions to this library

**Comment by excid3** [comment]
Slideover was added today thanks to @julianrubisch 🙏
