### ISSUE TITLE
Do you also need to install Tailwind CSS into Rails before using this? 

### ISSUE THREAD

**Issue by k2director** [excid3/tailwindcss-stimulus-components#42]
Sorry for beginner question, but the docs explicitly say you need StimulusJS installed (and I have that) but don't mention needing Tailwind CSS installed. I wasn't sure if Tailwind was installed simply by running: 

yarn add tailwindcss-stimulus-components

Without having Tailwind installed, I did run the yarn command but after registering/importing everything in application.js, no Tailwind markup seems to display in my views...

Thanks!

**Comment by excid3** [comment]
Yep, tailwind and stimulus are required. We should probably add tailwind as a peer dependency as well.

**Comment by k2director** [comment]
Thanks much, got it working with a little help from RailsBytes! ;-)
