### ISSUE TITLE
Example YouTube video no longer exists in demo page

### ISSUE THREAD

**Issue by nickjj** [excid3/tailwindcss-stimulus-components#45]
Steps to reproduce:

1. Head over to the demo page at https://excid3.github.io/tailwindcss-stimulus-components
2. Goto the "Tabs" example
3. Click the third tab
4. You'll see a broken YouTube embed
5. The referenced video is also no longer available on YouTube at https://youtu.be/y3niFzo5VLI
6. The same broken reference is in the "Tabs with Anchors" example too

The workaround for now is to manually inspect the iframe and change it to use a working video. I would have opened a PR to fix this but picking which video to use in the demo page is a very personal decision for @excid3 to pick!

**Comment by excid3** [comment]
It's way too tempting to change it to Rick Astley. 😈
