### ISSUE TITLE
suggestion : select

### ISSUE THREAD

**Issue by cprodhomme** [excid3/tailwindcss-stimulus-components#47]
Hello

thanks for your work.

I just want to know if you plan to inplemante select with tailwindcss/stimulus ?

**Comment by excid3** [comment]
You'll have to give some more detail as to what you're looking for. The tailwindcss-forms package already provides styling for select boxes. https://tailwindcss-forms.vercel.app/

**Comment by cprodhomme** [comment]
Hello, thanks for your answer.

I would like to make a custom select like this : https://tailwindui.com/components/application-ui/forms/select-menus
but for mobile, it's possible that it's not the best implementation 🤔

**Comment by excid3** [comment]
Our drop-down component is basically the same and could be used for that I think.
