### ISSUE TITLE
Are you open to a PR for a color picker preview (complete with YIQ calculations)?

### ISSUE THREAD

**Issue by nickjj** [excid3/tailwindcss-stimulus-components#72]
Hi,

I wanted to open this issue before opening a PR to see if you would be open to merging such a component. Technically the component itself isn't related to Tailwind, AKA there's no hard reference to any class names in the component.

### Use case

If a user doesn't upload an avatar you could display this instead. The preview aspect is useful for when you're picking the color in your profile and want to see a real time client side preview of what it looks like based on the color you picked.

### Current implementation

This is the default HTML5 color form field with a `<p>` to act as the preview. All of the classes are Tailwind but at this point the Tailwind specific stuff is sitting outside of the Stimulus component since it's just sitting in your HTML.

#### Picking a darker color

![image](https://user-images.githubusercontent.com/813219/115123265-347f6700-9f8a-11eb-99ca-0db15db40e07.png)

#### Picking a lighter color

![image](https://user-images.githubusercontent.com/813219/115123284-43661980-9f8a-11eb-9aa8-876a3c252913.png)

It automatically sets the foreground or background text to be visible based on the [YIQ calculation](https://24ways.org/2010/calculating-color-contrast/) which is only a few lines of code.

#### Options

It lets you choose whether or not you want to set the `color` or `backgroundColor` of your preview target.

**Comment by excid3** [comment]
A color picker would be awesome. 👍

I always wondered how the text color was calculated but never looked into it. YIQ is neat!

**Comment by nickjj** [comment]
Cool, the PR is https://github.com/excid3/tailwindcss-stimulus-components/pull/73.
