### ISSUE TITLE
Do you think we should hide `menu` and `toggleable` on disconnect?

### ISSUE THREAD

**Issue by A7madXatab** [excid3/tailwindcss-stimulus-components#81]
Hi, so i have been seeing weird behaviour on using the dropdown and other items, 

https://user-images.githubusercontent.com/38360603/116811540-9c20df00-ab52-11eb-9724-e6c47866b956.mov

I sovled the issue by extending the dropdown component and doing this 

```javascript
import { Dropdown } from "tailwindcss-stimulus-components"

export default class extends Dropdown {
    static targets = ["button"];

    disconnect() {
        this._hide();
    }
}
```

i would like to create a PR that addresses this if it's desired. This would also elimnate calling `dropdown#toggle` when using dropdown items.

?

**Comment by davegudge** [comment]
There are a couple of suggestions outlined on https://github.com/excid3/tailwindcss-stimulus-components/issues/63 to address this issue. 

I ended up using https://github.com/excid3/tailwindcss-stimulus-components/pull/65 which allows you to specific if a dropdown selection should close the dropdown menu itself.
