### ISSUE TITLE
Modal open by default?

### ISSUE THREAD

**Issue by bradherman** [excid3/tailwindcss-stimulus-components#88]
Is there a way to have a modal be open by default?

**Comment by excid3** [comment]
Just add the active classes to the HTML when you first render it. 👍

**Comment by bradherman** [comment]
Figured it out... I was trying to call the `open()` function, but that expects an event with a target... To make this be open, you need to:

1. Remove the hidden classes
2. Add the active classes
3. Copy/paste the overlay code from this gem's js into your modal
4. Extend the modal class, with a new controller and add into the `connect()` function `this.background = document.querySelector("#overlayId");`

**Comment by excid3** [comment]
I think you can also trigger the open event manually with JS as well by listening to the event on the controller element and dispatching it.

```html
<data-controller="modal" data-action="open->modal#open">
```

```javascript
let event = new CustomEvent("open")
document.querySelector("modal").dispatch(event)
```
