### ISSUE TITLE
Dropdown component animation flickering

### ISSUE THREAD

**Issue by thebluber** [excid3/tailwindcss-stimulus-components#97]
Hey, thanks for the amazing work by the way.
I followed the README to apply these data attributes e.g. `data-dropdown-invisible-class` and `data-dropdown-visible-class` for adding dropdown menu animation. But then I got a flickering appearance of the dropdown menu div when refreshing the page. After some digging I figured out that we are supposed to add these classes to the menu div `transform transition hidden opacity-0 scale-95`.
It's not an issue here I'm just wondering whether it is possible to add this bit of information to the README?

**Comment by thebluber** [comment]
yes gladly 😄 https://github.com/excid3/tailwindcss-stimulus-components/pull/98

**Comment by excid3** [comment]
Thanks a bunch for that!

**Comment by thebluber** [comment]
you're welcome
